import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs'

export default function Home() {
  const url = `https://api.openweathermap.org/data/2.5/weather?q=vancouver&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    // Fetching the data
    axios.get(url).then((response) => {
      setWeather(response.data)
      console.log(response.data)
    });
    // Resetting the search query and loading 
    setCity('');
    setLoading(false);
  }

  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Image overlay to reduce sharpness */}
      <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]" />

      {/* Background Image pulled from Unsplash */}
      <Image
        src="https://images.unsplash.com/photo-1562806568-a3450b810449?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80"
        alt="Sunny sky with clouds"
        layout="fill"
        className="object-cover"
      />

      {/* Input for Search */}

    </div>
  );
}
