import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs'

export default function Home() {
  const url = `https://api.openweathermap.org/data/2.5/weather?q=vancouver&appid=${process.env.WEATHER_KEY}`;

  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    // Fetching the data
    axios.get(url).then((response) => {
      setWeather(response.data)
      console.log(response.data)
    });
    // Resetting the search query and loading 
    setCity('');
    setLoading(false);
  }

  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
